development:
  adapter: postgresql
  database: pops5
  host: 172.30.1.5
  port: 5432
  timeout: 10000
  username: popsadm
  password: 'Nh;aqwzsx1414'
  encoding: utf8

  # production:
  # adapter: postgresql
  # database: pops
  # host: pgiuem.univ-brest.fr
  # username: popsadm
  # password: aB-jCorwWzfhor
  # encoding: utf8
